[package]
name = "sortable_rocksdb_keys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = "0.21.0"
enum_dispatch = "0.3.12"

[lib]
name = "rocks_sortable_keys"
path = "src/lib.rs"
